collections:
  - name: amazon.aws 
    version: 3.2.0
    source: https://galaxy.ansible.com/

  - name: community.aws 
    version: 3.2.1
    source: https://galaxy.ansible.com/

  - name: ansible_ssa.general
    version: 3.2.88
    source: https://ahub/api/galaxy/content/published/
  
  - name: community.general
    version: 4.8.0
    source: https://galaxy.ansible.com/

