---
controller_execution_environments:
  - name: "vmware-ee"
    description: ""
    organization: "Demo Org"
    image: "ghcr.io/red-hat-emea-portfolio-ssa/bcl_uc2:1"
    pull: "missing"
    credential: "Amaya ghcr"
  - name: "Amaya SNOW EE"
    description: ""
    organization: "Demo Org"
    image: "quay.io/amayagil/ee-amaya-snow"
    pull: "missing"
    credential: "amaya quay"
  - name: "Minimal execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "Ansible Engine 2.9 execution environment"
    description: ""
    image: "ahub.cibeles.me/ansible-automation-platform-22/ee-29-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "Default execution environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "Control Plane Execution Environment"
    description: ""
    image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
    pull: ""
    credential: "Default Execution Environment Registry Credential"
  - name: "Automation Hub Minimal execution environment"
    description: ""
    image: "ahub.cibeles.me/ee-minimal-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Automation Hub Ansible Engine 2.9 execution environment"
    description: ""
    image: "ahub.cibeles.me/ee-29-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Automation Hub Default execution environment"
    description: ""
    image: "ahub.cibeles.me/ee-supported-rhel8:latest"
    pull: ""
    credential: "Automation Hub Container Registry"
  - name: "Ansible SSA EE"
    description: ""
    image: "quay.io/redhat_emp1/ee-ansible-ssa:latest"
    pull: "always"
    credential: "amaya quay"
  - name: "Ansible SSA EE UNSTABLE"
    description: ""
    image: "quay.io/redhat_emp1/ee-ansible-ssa:unstable"
    pull: "always"
    credential: "amaya quay"
  - name: "Azure Execution Environment"
    description: ""
    image: "quay.io/cfernand/ee-azure-image:1.3"
    pull: "missing"
...
