---
# vars file for insights-registration
auto_config: "{{ auto_config | default(omit) }}"
authmethod: "{{ authmethod | default(omit) }}"
display_name: "{{ insights_display_name | default(omit) }}"
proxy: "{{ insights_proxy | default(omit) }}"