---
- name: "AAP Configuration as Code (CaC) - Entry Point"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # --- Configuración de Conexión Gateway ---
    gateway_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    gateway_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    gateway_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    gateway_validate_certs: "{{ vault_controller_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) | default(false) | bool }}"

  roles:
    - role: roles/role-aap-config-manager
      vars:
        aap_action: "{{ aap_action | default('extract') }}"