---
- name: Remediate CVEs in Red Hat Enterprise Linux machines registered to Red Hat Insights
  hosts: localhost
  gather_facts: true

  vars:
    cves: []

  tasks:
    - name: debug
      ansible.builtin.debug:
        msg: "kk"
        
    - name: Prepare machines for Insights Remediation
      ansible.builtin.include_role:
        name: role-insights-remediation
      when: ansible_os_family == 'RedHat'

- name: Run CVEs remediation in Red Hat Enterprise Linux machines
  hosts: "{{ dns_name }}"
  gather_facts: true

  tasks:
  - name: Run Insights to update data on "{{ dns_name }}"
    ansible.builtin.shell:
      cmd: insights-client 
    changed_when: false
    when: 
      - ansible_os_family == 'RedHat'
      - ansible_facts['distribution'] == "RedHat"