---
- name: Remediate CVEs in Red Hat Enterprise Linux machines registered to Red Hat Insights
  hosts: localhost
  gather_facts: true

  vars:
    cves: []

  tasks:
    - name: Prepare machines for Insights Remediation
      ansible.builtin.include_role:
        name: role-insights-remediation
      when: ansible_os_family == 'RedHat'