---
- name: Destroy EC2 instance
  hosts: all
  gather_facts: false

  tasks:
    - name: debug info
      debug:
        msg: "ec2_vpc_name: {{ ec2_vpc_name }} ec2_region: {{ ec2_region }}"
    - name: Deploy AWS instance
      vars:
        ec2_region: "eu-central-1"
        type: "{{ item.type}}"
        instance_name: "{{ item.name }}"
        ec2_os_type: "{{ item.ec2_os_type}}"
        windows_admin_password: "{{ item.windows_admin_password }}"
        remove: yes
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"