---
- name: Destroy EC2 instance
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Unregister Insights Client
      ansible.builtin.command: insights-client --unregister
      become: true
      ignore_errors: true
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"
    
    - name: Unregister RHSM
      community.general.redhat_subscription:
        state: absent
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
      become: true
      ignore_errors: true
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"

  tasks:
    - name: Deploy AWS instance
      vars:
        ec2_region: "eu-central-1"
        type: "{{ item.type}}"
        instance_name: "{{ item.name }}"
        ec2_os_type: "{{ item.ec2_os_type}}"
        ec2_key_pair: '{{ lookup("file","/tmp/id_rsa.pub") }}'
        windows_admin_password: "{{ item.windows_admin_password }}"
        remove: yes
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"