---
- name: Destroy EC2 instance
  hosts: all
  gather_facts: false

  tasks:
    - name: Deploy AWS instance
      vars:
        ec2_region: "eu-central-1"
        type: "{{ item.type}}"
        instance_name: "{{ item.name }}"
        ec2_os_type: "{{ item.ec2_os_type}}"
        ec2_key_pair: '{{ lookup("file","/tmp/id_rsa.pub") }}'
        windows_admin_password: "{{ item.windows_admin_password }}"
        remove: yes
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"