---
- name: Destroy EC2 instance
  hosts: all
  gather_facts: false

  tasks:
    - name: Deploy AWS instance
      vars:
        type: ec2
        remove: yes
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
