---
- name: Install Automation Controller
  hosts: all
  gather_facts: false
  vars:
    instance_name: "rhel-demo1"

  pre_tasks:
    - name: install python3-dnf
      ansible.builtin.dnf:
        name: python3-dnf
        state: present

  tasks:
    - name: Install an Automation Controller
      vars:
        controller_admin_password: "redhat"
        controller_pg_password: "redhat"
        controller_ah_enable: true
        controller_ah_instance_name: "rhel-demo1"
        username: "amaya.gil"
        password: "ba58o35s"


      ansible.builtin.include_role:
        name: ansible_ssa.general.controller_setup
