---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: true
  vars:
    instance_name: "rhel-demo1"

  pre_tasks:
    - name: What is my inventory_hostname
      debug: 
        msg: "inventory_hostname: {{ inventory_hostname }}"

    - name: What is my ansible_hostname
      debug: 
        msg: "ansible_hostname: {{ ansible_hostname }}"

  tasks:
    - name: Prepare machines with RHSM Registration
      ansible.builtin.include_role:
        name: rhsm-registration
      
    - name: Prepare machines with Insights Registration
      ansible.builtin.include_role:
        name: insights-registration