---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: true

  tasks:
    - name: Prepare machines with RHSM Registration
      ansible.builtin.include_role:
        name: rhsm-registration
      when: ansible_os_family == 'RedHat'
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"
      register: rhsm_out
      
    - name: Prepare machines with Insights Registration
      ansible.builtin.include_role:
        name: insights-registration
      when: ansible_os_family == 'RedHat'
      loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"