---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: true
  vars:
    instance_name: "rhel-demo1"

  pre_tasks:
    - name: What is my inventory_hostname
      debug: 
        msg: "inventory_hostname: {{ inventory_hostname }}"

    - name: What is my ansible_hostname
      debug: 
        msg: "ansible_hostname: {{ ansible_hostname }} corriendo OS {{ ansible_os_family }}"

    - name: rhsm vars
      debug:
        msg: "username: {{ rhsm_username | default (none) }} password: {{ rhsm_password }} pool_ids: {{ rhsm_poolid }} org_id: {{ org_id }} ak: {{ activationkey }}"
      ignore_errors: yes

    - name: insights vars
      debug: 
        msg: "rhsm_username: {{ rhsm_username }} auto_config: {{ auto_config }} authmethod: {{ authmethod }} display_name: {{ display_name }}"

  tasks:
    - name: Prepare machines with RHSM Registration
      ansible.builtin.include_role:
        name: rhsm-registration
      when: ansible_os_family == 'RedHat'
      #loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"
      register: rhsm_out

    - name: salida rhsm-registration
      debug: 
        msg: "rhsm_out: {{ rhsm_out.out }}"
      
    - name: Prepare machines with Insights Registration
      ansible.builtin.include_role:
        name: insights-registration
      when: ansible_os_family == 'RedHat'
      #loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"