---
- name: Prepare machines to show Insights vulnerability
  hosts: all
  gather_facts: true

  tasks:
    - name: Install the Adobe rpm from a remote repo
      ansible.builtin.dnf:
        name: 'http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm'
        state: present
        disable_gpg_check: true
      when: ansible_os_family == 'RedHat'
      
    - name: Install Adobe plugin and its dependencies
      ansible.builtin.dnf:
        name:
          - libcurl
          - flash-plugin
          - alsa-plugins-pulseaudio
        state: latest
      when: ansible_os_family == 'RedHat'
      register: aplug_out
      
    # create advisor issues to fix
    - name: Set too open perms to sshd config file
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        state: file
        mode: u+rwx,g+rwx,o-+rwx

    - name: Allow Empty Passwords on sshd
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: "PermitEmptyPasswords no"

    - name: Allow Root login on sshd
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: "PermitRootLogin yes"

    - name: Run Insights to update data
      ansible.builtin.command: insights-client
      changed_when: false
      when: ansible_os_family == 'RedHat'
