---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: true
  vars:
    instance_name: "rhel-demo1"

  pre_tasks:
    - name: What is my inventory_hostname
      debug: 
        msg: "inventory_hostname: {{ inventory_hostname }}"

    - name: What is my ansible_hostname
      debug: 
        msg: "ansible_hostname: {{ ansible_hostname }}"

    - name: insights vars
      debug: 
        msg: "rhsm_username: {{ rhsm_username }} auto_config: {{ auto_config }} authmethod: {{ authmethod }} display_name: {{ display_name }}"
    
    - name: file content 
      debug: 
        msg: "the value of foo.txt is {{lookup('file', 'templates/insights-client.conf.j2') }}"


  tasks:
    - name: Prepare machines with RHSM Registration
      ansible.builtin.include_role:
        name: rhsm-registration
      when: ansible_os_family == 'RedHat'
      #loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"
      
    - name: Prepare machines with Insights Registration
      ansible.builtin.include_role:
        name: insights-registration
      when: ansible_os_family == 'RedHat'
      #loop: "{{ lookup('file', 'machines.yml') | from_yaml }}"