---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: true

  tasks:
    - name: Prepare machines with RHSM Registration
      ansible.builtin.include_role:
        name: role-rhsm-registration
      when: ansible_os_family == 'RedHat'
      register: rhsm_out
      
    - name: Prepare machines with Insights Registration
      ansible.builtin.include_role:
        name: role-insights-registration
      when: ansible_os_family == 'RedHat'

    - name: Prepare machines with Red Hat Cloud Connector
      ansible.builtin.include_role:
        name: role-rhc-install
      when: ansible_os_family == 'RedHat'

    - name: Prepare machines for Insights Malware detection
      ansible.builtin.include_role:
        name: role-malware-detection-conf
      when: ansible_os_family == 'RedHat'