---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: true

  vars:
    msg_slack: "Instances registed to Red Hat services"
    msg_tlg: "Instances registed to Red Hat services"

  tasks:
    - name: debug IPs
      debug:
        msg: "ansible host {{ ansible_host }} nombre {{ ansible_hostname }} IP {{  ansible_default_ipv4.address }}"

    - name: Prepare machines with RHSM Registration
      ansible.builtin.include_role:
        name: role-rhsm-registration
      when: ansible_os_family == 'RedHat'
      register: rhsm_out
      
    - name: Prepare machines with Insights Registration
      ansible.builtin.include_role:
        name: role-insights-registration
      when: ansible_os_family == 'RedHat'

    - name: Prepare machines with Red Hat Cloud Connector
      ansible.builtin.include_role:
        name: role-rhc-install
      when: ansible_os_family == 'RedHat'