---
- name: Prepare machines to show Insights vulnerability
  hosts: all
  gather_facts: true

  tasks:
    - name: Prepare for FinSpy
      ansible.builtin.shell:
        cmd: |
          echo "fin_conn_" "fin_relay_" "fin_util_"
          echo "fin_read_" "fin_conf"
      when: ansible_os_family == 'RedHat'

    - name: Force Insights Malware detection
      ansible.builtin.command: insights-client --collector malware-detection
      become: true
      when:
      - ansible_os_family == 'RedHat'
      - ansible_facts['distribution'] == "RedHat"
      - ansible_facts['distribution_version'] is version('8.0', '>=')