---
- name: Prepare machines to show Insights vulnerability
  hosts: all
  gather_facts: true

  tasks:
    - name: Prepare for FinSpy
      ansible.builtin.shell: |
        echo: "fin_conn_" "fin_relay_" "fin_util_"
        echo: "fin_read_" "fin_conf"
      when: ansible_os_family == 'RedHat'
