---
- name: instalar rhc
  hosts: servera.lab.example.com
  become: true
  gather_facts: true

  vars:
    os: "{{ ansible_distribution }}"

  tasks:
    - name: ver os
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} "
      tags: el86

    - name: habilitar repo 
      community.general.rhsm_repository:
        name: ansible-2.9-for-rhel-8-x86_64-rpms 
        state: enabled
      register: salida
      when: rhsm.changed == true
      tags: el86
      ignore_errors: yes

    - name: instalar paquete rhc para el8.5
      ansible.builtin.dnf:
        name: rhc-worker-playbook-0.1.5-3.el8_4
      when:
        - ansible_facts['distribution'] == "Red Hat"
        - ansible_facts['distribution_version'] == "8.5"
      tags: never

    - name: instalar paquete rhc para el8.6 y posteriores
      ansible.builtin.dnf:
        name: 
          - rhc
          - rhc-worker-playbook
          - ansible-core
        state: latest
      when:
        - ansible_facts['distribution'] == "Red Hat"
        - ansible_facts['distribution_version'] >= "8.6"
      tags: el86
