---
- name: Prepare machines for use with Red Hat
  hosts: localhost
  gather_facts: true

  vars:
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"
    insights_api_url: "https://console.redhat.com/api"
    recommendation_id: "{{ recommendation_id}}"
    cves: []
    #playbook: playbook.yml

  tasks:
    - name: Pull info from Insights API
      ansible.builtin.uri:
        url: "{{ insights_api_url }}/vulnerability/v1/vulnerabilities/cves?affecting=true"
        method: GET
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: true
        return_content: yes
      register: cve_list
      #failed_when: cve_list is failed or "'CVE' not in cve_list.content"

    - name: Set result json as fact
      ansible.builtin.set_fact:
        cve_list_data_json: "{{ (cve_list.content | from_json).data }}"

    - name: List ALL data of ALL CVEs
      ansible.builtin.debug:
        msg: 
        - "CVE Description: {{ item.attributes.description }}"
        - "CVE Synopsis: {{ item.attributes.synopsis }}"
        - "CVE Impact: {{ item.attributes.impact }}"
        verbosity: 0
      loop: "{{ cve_list_data_json }}"

    - name: Initilize Cves list
      set_fact:
        cves: []

    - name: Cve list - prova questo
      ansible.builtin.set_fact:
        #cves: '{{ cves | default([]) + [ {"id": "{{ item.id }}" } ] }}'
        cves: "{{ cves + [ item.id ] }}"
      loop: "{{ cve_list_data_json }}"
        
    - name: List of system affected by CVEs
      ansible.builtin.uri:
        url: "{{ insights_api_url }}/vulnerability/v1/cves/{{ item }}/affected_systems"
        method: GET
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: true
        return_content: yes
      register: hosts_cves
      loop: "{{ cves }}"

    - name: Set result json as fact
      ansible.builtin.set_fact:
        host_cve_list_data_json: "{{ (cve.content | from_json).data }}"

    - name: Display system details
      ansible.builtin.debug:
        msg: "{{ host_cve_list_data_json }}"
      
#
#    - name: Display system details
#      ansible.builtin.debug:
#        var: "{{ cve_list_data_json }}"
        #var: "{{ cve_list_json | community.general.json_query('[data]') }}"
