---
- name: Prepare machines for use with Red Hat
  hosts: localhost
  gather_facts: true

  vars:
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"
    insights_api_url: "https://console.redhat.com/api"
    recommendation_id: "{{ recommendation_id}}"
    #playbook: playbook.yml

  tasks:
    - name: Pull info from Insights API
      ansible.builtin.uri:
        url: "{{ insights_api_url }}/vulnerability/v1/vulnerabilities/cves?affecting=true"
        method: GET
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: true
        return_content: yes
      register: insights_api
      #failed_when: insights_api is failed or "'CVE' not in insights_api.content"

    - name: Show what type of variable insights_api is
      ansible.builtin.debug:
        msg: "{{ insights_api.content | from_json }}"

#    - name: Show what type of data the insights_api variable is made up of
#      ansible.builtin.debug:
#        msg: "{{ item | type_debug }}"
#      loop: "{{ insights_api.content['data'] }}"
#
#    - name: set facts
#      set_fact: 
#        insights_api_content: "{{ insights_api.content }}"
#
#    - name: List ALL data of ALL CVEs
#      ansible.builtin.debug:
#        msg: "{{ insights_api_content | selectattr('data', 'defined') | map(attribute='data') }}"
#
    - name: Display system details
      ansible.builtin.debug:
        var: "{{ insights_api.content.data[0] }}"

#    - name: Ver cositas
#      debug:
#        msg:
#        - "CVE Score: {{ insights_api.content.data[0].attributes.cvss3_score }}"
#        - "CVE Description: {{ insights_api.content.data[0].attributes.description }}"
#        - "CVE Synopsis: {{ insights_api.content.data[0].attributes.synopsis }}"
#        - "CVE Impact: {{ insights_api.content.data[0].attributes.impact }}"
#    - name: Display system facts
#      debug:
#        msg:
#        - "display_name: {{ insights_api.json.insights_apis[0].display_name }}"
#        - "fqdn: {{ insights_api.json.insights_apis[0].fqdn }}"
#        - "insights_id: {{ insights_api.json.insights_apis[0].insights_id }}"
#        - "id: {{ insights_api.json.insights_apis[0].id }}"