---
- name: Prepare machines for use with Red Hat
  hosts: localhost
  gather_facts: true

  vars:
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"
    insights_api_url: "https://console.redhat.com/api"
    recommendation_id: "{{ recommendation_id}}"
    #playbook: playbook.yml

  tasks:
    - name: pull info from Insights API
      ansible.builtin.uri:
        url: "{{ insights_api_url }}/vulnerability/v1/vulnerabilities/cves?affecting=true"
        #url: "{{ insights_api_url }}/vulnerability/v1/vulnerabilities/cves"
        method: GET
        return_content: true
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: yes
      #failed_when: result is failed or "'CVE' not in result.content"
      register: instights_api

    - name: Display system details
      ansible.builtin.debug:
        var: instights_api.json

#    - name: Ver cositas
#      debug:
#        msg:
#        - "CVE Score: {{ result.content.data[0].attributes.cvss3_score }}"
#        - "CVE Description: {{ result.content.data[0].attributes.description }}"
#        - "CVE Synopsis: {{ result.content.data[0].attributes.synopsis }}"
#        - "CVE Impact: {{ result.content.data[0].attributes.impact }}"
#    - name: Display system facts
#      debug:
#        msg:
#        - "display_name: {{ result.json.results[0].display_name }}"
#        - "fqdn: {{ result.json.results[0].fqdn }}"
#        - "insights_id: {{ result.json.results[0].insights_id }}"
#        - "id: {{ result.json.results[0].id }}"