---
- name: Prepare machines for use with Red Hat
  hosts: all
  gather_facts: false

  vars:
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"
    insights_api_url: "https://cloud.redhat.com/api"
    recommendation_id: "{{ recommendation_id}}"
    #playbook: playbook.yml

  tasks:
    - name: pull info from Insights API
      ansible.builtin.uri:
        url: "{{ insights_api_url }}/vulnerability/v1/vulnerabilities/cves?affecting=true"
        method: GET
        return_content: true
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: yes
      register: this
      failed_when: this is failed or "'CVE' not in this.content"
      when: ansible_os_family == 'RedHat'