---
- name: Prepare machines for use with Red Hat
  hosts: localhost
  gather_facts: true

  vars:
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"
    insights_api_url: "https://console.redhat.com/api"
    recommendation_id: "{{ recommendation_id}}"
    #playbook: playbook.yml

  tasks:
    - name: Pull info from Insights API
      ansible.builtin.uri:
        url: "{{ insights_api_url }}/vulnerability/v1/vulnerabilities/cves?affecting=true"
        method: GET
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: true
      register: instights_api
      #failed_when: instights_api is failed or "'CVE' not in instights_api.content"

    - name: Display system details
      ansible.builtin.debug:
        var: instights_api.json

#    - name: Ver cositas
#      debug:
#        msg:
#        - "CVE Score: {{ instights_api.content.data[0].attributes.cvss3_score }}"
#        - "CVE Description: {{ instights_api.content.data[0].attributes.description }}"
#        - "CVE Synopsis: {{ instights_api.content.data[0].attributes.synopsis }}"
#        - "CVE Impact: {{ instights_api.content.data[0].attributes.impact }}"
#    - name: Display system facts
#      debug:
#        msg:
#        - "display_name: {{ instights_api.json.instights_apis[0].display_name }}"
#        - "fqdn: {{ instights_api.json.instights_apis[0].fqdn }}"
#        - "insights_id: {{ instights_api.json.instights_apis[0].insights_id }}"
#        - "id: {{ instights_api.json.instights_apis[0].id }}"