---
- name: "Eliminar Token de Autenticación"
  ansible.builtin.include_tasks: manage_token.yml
  vars:
    token_state: absent

- name: "Eliminar archivos temporales (Opcional)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ backup_local_dir }}"
  when: cleanup_after_export | default(false)
