---
# roles/role-aap-config-manager/tasks/extract_tasks.yml

- name: "Forzar variables globales para dominar al Lookup Plugin"
  ansible.builtin.set_fact:
    controller_hostname: "{{ aap_hostname }}"
    controller_host: "{{ aap_hostname }}"
    controller_username: ""
    controller_password: ""

- name: "DEBUG: Verificar qué hay en la memoria de Ansible vs el Sistema Operativo"
  ansible.builtin.debug:
    msg:
      - "1. Fact controller_hostname: '{{ controller_hostname }}'"
      - "2. Fact controller_host: '{{ controller_host }}'"
      - "3. Fact controller_username: '{{ controller_username }}'"
      - '4. SO ENV CONTROLLER_HOST: {{ lookup("env", "CONTROLLER_HOST") }}'
      - '5. SO ENV CONTROLLER_USERNAME: {{ lookup("env", "CONTROLLER_USERNAME") }}'

- name: "Generar estructura de archivos desde el Controller (IaC)"
  environment:
    CONTROLLER_HOST: "{{ aap_hostname | regex_replace('/$','') }}"
    CONTROLLER_API_PATH: "{{ controller_api_path }}"
    CONTROLLER_USERNAME: "{{ aap_username | default('') }}"
    CONTROLLER_PASSWORD: "{{ aap_password | default('') }}"
  block:
    - name: "Call infra.controller_configuration.filetree_create"
      ansible.builtin.include_role:
        name: infra.controller_configuration.filetree_create
      vars:
        controller_oauthtoken: "{{ aap_oauthtoken }}"
        controller_api_path: >-
          {{ '/api/v2' if (controller_source_version is defined and controller_source_version == '2.4') else (vault_controller_api_path | default(lookup('env', 'CONTROLLER_API_PATH'), true) | default('/api/controller/v2', true)) }}
        controller_hostname: >-
          {{ aap_hostname if (controller_source_version is defined and controller_source_version == '2.4') else aap_hostname ~ '/api/controller' }}
        dir_orgs_vars: "{{ base_dir | default(playbook_dir ~ '/platform_configuration') }}"
        orgs: "all"
        env: "dev"
        query_controller_api: true
        valid_tags:
          - all
          - organizations
          - projects
          - inventories
          - credentials
          - credential_types
          - job_templates
          - workflow_job_templates
          - roles
      register: _filetree_output
      ignore_errors: "{{ aap_dry_run | default(false) | bool }}"
  
- name: "Revocar token tras la extracción"
  ansible.builtin.uri:
    url: >-
      {{ controller_api_path if controller_api_path is match('^https?://') else (aap_hostname | regex_replace('/$','')) + controller_api_path }}/tokens/{{ authtoken_res.json.id }}/
    method: DELETE
    headers:
      Authorization: "Bearer {{ aap_oauthtoken }}"
    validate_certs: "{{ aap_validate_certs | default(false) | bool }}"
    status_code: 204
  when: aap_oauthtoken is defined and not (aap_dry_run | default(false) | bool)
  ignore_errors: true