---
# roles/role-aap-config-manager/tasks/inject.yml

- name: "Asegurar variables para el estándar de AAP 2.6"
  set_fact:
    # Mapeamos tus organizaciones al nombre que espera el rol de gateway
    aap_organizations: "{{ controller_organizations | default([]) }}"
    # Definimos la base de la API usando el hostname del gateway
    aap_gateway_api_base: "{{ (controller_target_version is version('2.6', '>=')) | ternary(aap_gateway_hostname ~ '/api/controller/v2', aap_gateway_hostname ~ '/api/v2') }}"
    # Replicamos las credenciales como hechos (facts) para asegurar su propagación
    aap_gateway_hostname: "{{ aap_gateway_hostname }}"
    aap_gateway_username: "{{ aap_gateway_username }}"
    aap_gateway_password: "{{ aap_gateway_password }}"

- name: "Flujo de Extracción: Pre-flight checks"
  ansible.builtin.include_tasks: preflight.yml

- name: "Inyección: Validar archivos de origen"
  ansible.builtin.include_tasks: validate.yml

- name: "Normalización: Normalizar archivos de origen"
  ansible.builtin.include_tasks: normalize.yml

- name: "Inyección: Ejecutar carga de datos (Dispatch)"
  ansible.builtin.include_tasks: inject_tasks.yml