---
# roles/aap_config_manager/tasks/inject_tasks.yml

- name: "Configurar Base para Inyección"
  set_fact:
    gateway_api_base: "{{ (controller_target_version is version('2.6', '>=')) | ternary(aap_gateway_hostname ~ '/api/controller/v2', aap_gateway_hostname ~ '/api/v2') }}"

- name: "Mapear variables para el estándar de la colección"
  set_fact:
    # Aseguramos que los datos de los backups lleguen a los roles de gateway
    aap_organizations: "{{ controller_organizations | default([]) }}"

- name: "Inyección: Ejecutar Pre-vuelo"
  ansible.builtin.include_tasks: preflight.yml

- name: "Inyección: Validar archivos de origen"
  ansible.builtin.include_tasks: validate.yml

- name: "Normalización: Normalizar archivos de origen"
  ansible.builtin.include_tasks: normalize.yml

- name: "Inyección: Ejecutar carga de datos (Dispatch)"
  ansible.builtin.include_tasks: inject_tasks.yml

- name: "Inyección: Limpieza de sesión"
  ansible.builtin.include_tasks: cleanup.yml

- name: "Inyección: Resumen de ejecución"
  ansible.builtin.include_tasks: summary.yml
