---
- name: "Leer contenido de {{ item.path | basename }}"
  ansible.builtin.set_fact:
    _raw_data: "{{ lookup('file', item.path) | from_yaml }}"
  ignore_errors: yes

- name: "Acumular objetos en memoria"
  ansible.builtin.set_fact:
    # Si la clave existe en el archivo, se suma a la lista. Si no, suma una lista vacía [].
    filetree_controller_organizations: "{{ filetree_controller_organizations + (_raw_data.controller_organizations | default([])) }}"
    filetree_controller_user_accounts: "{{ filetree_controller_user_accounts + (_raw_data.controller_user_accounts | default([])) }}"
    filetree_controller_credentials: "{{ filetree_controller_credentials + (_raw_data.controller_credentials | default([])) }}"
    filetree_controller_projects: "{{ filetree_controller_projects + (_raw_data.controller_projects | default([])) }}"
    filetree_controller_inventories: "{{ filetree_controller_inventories + (_raw_data.controller_inventories | default([])) }}"
    filetree_controller_templates: "{{ filetree_controller_templates + (_raw_data.controller_templates | default([])) }}"
    filetree_controller_workflows: "{{ filetree_controller_workflows + (_raw_data.controller_workflows | default([])) }}"
  when: 
    - _raw_data is defined
    - _raw_data is mapping
  ignore_errors: yes