---
# roles/role-aap-config-manager/tasks/process_item.yml

- name: "Preparar datos para: {{ item.role }}"
  ansible.builtin.set_fact:
    _current_loop_data: "{{ lookup('vars', 'filetree_' ~ item.var, default=[]) }}"

- name: "Inyectar datos"
  ansible.builtin.set_fact:
    "{{ item.var }}": "{{ _current_loop_data }}"
  when: _current_loop_data | length > 0

- name: "Ejecutar rol infra.controller_configuration.{{ item.role }}"
  ansible.builtin.include_role:
    name: "infra.controller_configuration.{{ item.role }}"
  vars:
    # Como la colección le va a añadir /api/v2/, nos aprovechamos de que Envoy 
    # de AAP 2.6 redirige internamente las peticiones antiguas SIEMPRE Y CUANDO
    # el token sea válido y la petición no sea async.
    controller_host: "https://{{ controller_hostname }}"
    controller_oauthtoken: "{{ controller_token }}" 
    controller_validate_certs: false
    
    # MUERTE TOTAL AL ASYNC EN EL BLOQUE VARS
    controller_configuration_async: false
    controller_configuration_organizations_async: false
    controller_configuration_users_async: false
    controller_configuration_credentials_async: false
    controller_configuration_projects_async: false
    controller_configuration_inventories_async: false
    controller_configuration_job_templates_async: false
    controller_configuration_workflow_job_templates_async: false
  when: _current_loop_data | length > 0