---
- name: "Validar existencia de datos para la acción: {{ aap_action }}"
  ansible.builtin.stat:
    # Usamos backup_local_dir para ambas acciones o aseguramos un fallback
    path: "{{ backup_local_dir | default('./backups') }}"
  register: _data_stat

- name: "Verificar integridad de la ruta"
  ansible.builtin.assert:
    that:
      - _data_stat.stat.exists
      - _data_stat.stat.isdir
    fail_msg: "ERROR: La ruta de datos no existe o no es un directorio."

- name: "Validar presencia de archivos YAML"
  ansible.builtin.find:
    paths: "{{ backup_local_dir | default('./backups') }}"
    patterns: "*.yaml"
    recurse: yes
  register: _found_yaml

- name: "Error si no hay archivos de configuración"
  ansible.builtin.assert:
    that:
      - _found_yaml.matched > 0
    fail_msg: "ERROR: No se han encontrado archivos .yaml en la ruta especificada."
