---
# vars file for insights-registration
auto_config: "{{ auto_config | default(omit) }}"
authmethod: "{{ authmethod | default(omit) }}"
display_name: "{{ ansible_fqdn | default(omit) }}"
proxy: "{{ insights_proxy | default(none) }}"
rhsm_username: "{{ rhsm_username | default(none) }}"
rhsm_password: "{{ rhsm_password | default(none) }}"
rhsm_poolid: "{{ rhsm_poolid | default(none) }}"
activationkey: "{{ activationkey | default(none) }}"
org_id: "{{ org_id | default(none) }}"