---
# tasks file for role
- name: habilitar repo para el8.5 
  community.general.rhsm_repository:
    name: ansible-2.9-for-rhel-8-x86_64-rpms 
    state: enabled
  register: salida
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_version'] is version('8.5', '==')
  
- name: ver costitans
  debug:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} {{ salida }}"

- name: arreglar el error 'Repositories disabled by configuration'
  ansible.builtin.command: subscription-manager config --rhsm.manage_repos=1
  register: output
  when: salida.rc != 0

- name: debug
  debug:
    msg: "{{ output }}"

- name: instalar paquete rhc para el8.5
  ansible.builtin.dnf:
    name: 
      - rhc-worker-playbook-0.1.5-3.el8_4
      - ansible
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_version'] is version('8.5', '==')

- name: instalar paquete rhc para el8.6 y posteriores
  ansible.builtin.dnf:
    name: 
      - rhc
      - rhc-worker-playbook
      - ansible-core
    state: latest
  when: 
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_version'] is version('8.6', '>=')