download_url: https://galaxy.ansible.com/download/ansible-eda-1.3.3.tar.gz
format_version: 1.0.0
name: eda
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.3.3
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/eda/versions/1.3.3/
