---
# tasks file for ah-install

- name: Enable required RHSM repositories
  community.general.rhsm_repository:
    name: 
      - ansible-automation-platform-{{ aap_version }}-for-rhel-8-x86_64-rpms
    state: enabled
  become: true

- name: Ensure all packages are updated
  ansible.builtin.yum:
    name: '*'
    state: latest
  become: true

- name: Create destination directory
  ansible.builtin.file:
    path: ~/aap2
    state: directory

- name: Extract AAP2 setup content
  ansible.builtin.unarchive:
    src: "{{ rh_product_path }}/{{ hostvars[inventory_hostname]['product_filename'] }}"
    dest: ~/aap2
    remote_src: yes

- name: Retrieve AAP2 folder name
  ansible.builtin.find:
    paths: ~/aap2
    file_type: directory
  register: untar

- name: Print var
  ansible.builtin.debug:
    var: untar.files[0].path

- name: Copy inventory for automation hub
  ansible.builtin.template:
    dest: "{{ untar.files[0].path }}/inventory"
    src: inventory-hub.j2
  become: true

- name: Install Automation Hub
  ansible.builtin.shell:
    cmd: ./setup.sh
    chdir: "{{ untar.files[0].path }}"
  become: true        

- name: Reboot server
  ansible.builtin.reboot:
  become: true