---
- name: Disabling SELinux to generate more input to Insights
  selinux:
    state: disabled

- name: Install yara package
  ansible.builtin.dnf:
    name: yara
    state: latest
  ignore_errors: true
  register: install

- name: Habilitar Insights Malware detection
  ansible.builtin.command: insights-client --collector malware-detection
  become: true
  when: 
  - ansible_os_family == 'RedHat'
  - ansible_facts['distribution'] == "RedHat"
  - ansible_facts['distribution_version'] is version('8.0', '>=')
  - install.changed == true
  
- name: Comprobar que el fichero de configuración existe
  ansible.builtin.stat:
    path: /etc/insights-client/malware-detection-config.yml
  register: salida
  when:
  - install.changed == true

- name: Disable test scan
  ansible.builtin.lineinfile:
    path: /etc/insights-client/malware-detection-config.yml
    search_string: 'test_scan: true'
    line: 'test_scan: false'
    owner: root
    group: root
    mode: '0644'
  when: 
  - salida.stat.exists
  - install.changed == true

- name: Reboot server to force scan without SELinux
  reboot:

- name: Forzar Insights Malware detection
  ansible.builtin.command: insights-client --collector malware-detection
  become: true
  when: 
  - ansible_os_family == 'RedHat'
  - ansible_facts['distribution'] == "RedHat"
  - ansible_facts['distribution_version'] is version('8.0', '>=')
  - install.changed == true

- name: Creates a cron file under /etc/cron.d para ejecutar la detección de malware diariamente
  ansible.builtin.cron:
    name: "malware auto update"
    weekday: "*"
    minute: "0"
    hour: "3"
    user: root
    job: "insights-client --collector malware-detection"
    cron_file: malware-autoupdate
  when: 
  - ansible_os_family == 'RedHat'
  - ansible_facts['distribution'] == "RedHat"
  - ansible_facts['distribution_version'] is version('8.0', '>=')
  - install.changed == true