---
- name: Install 'insights-client'
  yum:
    name: insights-client
  become: true

- name: Set Insights Configuration Values
  template:
    dest: /etc/insights-client/insights-client.conf
    src: templates/insights-client.conf.j2
  become: true

#- name: verificar q el fichero de config existe
#  stat:
#    path: /etc/insights-client/insights-client.conf
#  register: register_path

#- name: mostrar salida
#  debug:
#    msg: "The file or directory exists, {{ register_path }}"
#  when: register_path.stat.exists
- name: ver nombres de host
  debug:
    msg: "display_name: {{ display_name }} ansible_hostname: {{ ansible_hostname }} inventory_hostname: {{ inventory_hostname }} insights_display_name: {{ insights_display_name }} "
  
- name: Change permissions of Insights Config directory so that Insights System ID can be read
  file:
    path: /etc/insights-client
    mode: og=rx
  become: true

- name: Register Insights Client
  ansible.builtin.command: insights-client --register
  become: true

- name: Change permissions of machine_id file so that Insights System ID can be read
  file:
    path: /etc/insights-client/machine-id
    mode: og=r
  become: true

- name: Create directory for ansible custom facts
  file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d
  become: true

- name: Install custom insights fact
  copy:
    src: insights.fact
    dest: /etc/ansible/facts.d
    mode: a+x
  become: true