---
- name: Disabling SELinux to generate more input to Insights
  selinux:
    state: disabled

- name: Install yara package
  ansible.builtin.dnf:
    name: yara
    state: latest
    register: malos

- name: debug malos
  debug:
    msg: "malos es {{ malos }}"