---
- name: Disabling SELinux to generate more input to Insights
  selinux:
    state: disabled

- name: Install yara package
  ansible.builtin.dnf:
    name: yara
    state: latest

- name: Disable test scan
  ansible.builtin.lineinfile:
    path: /etc/insights-client/malware-detection-config.yml
    search_string: 'test_scan: true'
    line: 'test_scan: false'
    owner: root
    group: root
    mode: '0644'