---
- name: Disabling SELinux to generate more input to Insights
  selinux:
    state: disabled

- name: Install yara package
  ansible.builtin.dnf:
    name: yara
    state: latest

- name: Force Insights Malware detection
  ansible.builtin.command: insights-client --collector malware-detection --display-name {{ display_name }}
  become: true
  when: ansible_os_family == 'RedHat'
  register: malos

- name: output
  debug:
    msg: "malos"

- name: Disable test scan
  ansible.builtin.lineinfile:
    path: /etc/insights-client/malware-detection-config.yml
    search_string: 'test_scan: true'
    line: 'test_scan: false'
    owner: root
    group: root
    mode: '0644'
  register: linea

- name: output
  debug:
    msg: "linea"