---
- name: Disabling SELinux to generate more input to Insights
  selinux:
    state: disabled

- name: Install yara package
  ansible.builtin.dnf:
    name: yara
    state: latest

- name: Force Insights Malware detection
  ansible.builtin.command: insights-client --collector malware-detection
  become: true
  when: 
  - ansible_os_family == 'RedHat'
  - ansible_facts['distribution'] == "RedHat"
  - ansible_facts['distribution_version'] is version('8.0', '>=')
  
- name: Comprobar que el fichero de configuración existe
  ansible.builtin.stat:
    path: /etc/insights-client/malware-detection-config.yml
  register: salida

- name: Disable test scan
  ansible.builtin.lineinfile:
    path: /etc/insights-client/malware-detection-config.yml
    search_string: 'test_scan: true'
    line: 'test_scan: false'
    owner: root
    group: root
    mode: '0644'
  when: salida.stat.exists