---
# defaults file for ah-install
registry_url: "registry.redhat.io"
registry_username: ""
registry_password: ""

controller_instance_name: "{{ instance_name }}"
controller_ah_instance_name : "{{ controller_ah_instance_name }}"
aap_version: "2.2"
checksum_aap2: ""

automationhub_admin_password: "redhat"

automationhub_pg_host: ""
automationhub_pg_port: ""

automationhub_pg_database: "automationhub"
automationhub_pg_username: "automationhub"
automationhub_pg_password: "redhat"
automationhub_pg_sslmode: "prefer"