---
  - name: Run remediation playbooks
    ansible.builtin.include_playbook: 
      file: "{{ playbook_dir }}/{{ item.item.cve_id }}-remediation-{{ item.item.hostname }}.yml"
    loop: "{{ pbs_per_host.results }}"