---
  - name: Run CVE remediation playbook on "{{ dns_name }}"
    ansible.builtin.shell:
      cmd: ansible-playbook -i azure_rm.yml -e ansible_user="{{ ansible_user }}" -e ansible_password="{{ ansible_password }}" "{{ playbook_dir }}/{{ item.item.cve_id }}-remediation-{{ item.item.hostname }}.yml"
    loop: "{{ pbs_per_host.results }}"
    delegate_to: localhost
    when: 
      - cloud == 'azure'
      - ansible_os_family == 'RedHat'
      - ansible_facts['distribution'] == "RedHat"

  - name: Run CVE remediation playbook on "{{ dns_name }}"
    ansible.builtin.shell:
      cmd: ansible-playbook -i aws_ec2.yml -e ansible_user="{{ ansible_user }}" -e ansible_ssh_private_key_file="/runner/artifacts/{{ tower_job_id }}/ssh_key_data" "{{ playbook_dir }}/{{ item.item.cve_id }}-remediation-{{ item.item.hostname }}.yml"
    loop: "{{ pbs_per_host.results }}"
    delegate_to: localhost
    when: 
      - cloud == 'azure'
      - ansible_os_family == 'RedHat'
      - ansible_facts['distribution'] == "RedHat"
      - ansible_ssh_private_key_file is defined

  - name: Run CVE remediation playbook on "{{ dns_name }}"
    ansible.builtin.shell:
      cmd: ansible-playbook -i aws_ec2.yml -e ansible_user="{{ ansible_user }}" -e ansible_password="{{ ansible_password }}" "{{ playbook_dir }}/{{ item.item.cve_id }}-remediation-{{ item.item.hostname }}.yml"
    loop: "{{ pbs_per_host.results }}"
    delegate_to: localhost
    when: 
      - cloud == 'ec2'
      - ansible_os_family == 'RedHat'
      - ansible_facts['distribution'] == "RedHat"
      - ansible_password is defined

  - name: Run CVE remediation playbook on "{{ dns_name }}"
    ansible.builtin.shell:
      cmd: ansible-playbook -i aws_ec2.yml -e ansible_user="{{ ansible_user }}" -e ansible_ssh_private_key_file="/runner/artifacts/{{ tower_job_id }}/ssh_key_data" "{{ playbook_dir }}/{{ item.item.cve_id }}-remediation-{{ item.item.hostname }}.yml"
    loop: "{{ pbs_per_host.results }}"
    delegate_to: localhost
    when: 
      - cloud == 'ec2'
      - ansible_os_family == 'RedHat'
      - ansible_facts['distribution'] == "RedHat"
      - ansible_ssh_private_key_file is defined