---
# tasks file for role-insights-remediation
- ansible.builtin.include_tasks: 
    file: insights-inventory.yml

- ansible.builtin.include_tasks: 
    file: insights-cves.yml

- ansible.builtin.include_playbook: 
    file: "{{ playbook_dir }}/{{ item.item.cve_id }}-remediation-{{ item.item.hostname }}.yml"
  loop: "{{ pbs_per_host.results }}"