---
# tasks file for ah-install
- name: AAP Automation Hub configuration playbook
  tasks:
    - name: Create destination directory
      file:
        path: ~/aap2
        state: directory

    - name: Extract AAP2 setup content
      ansible.builtin.unarchive:
        src: "{{ controller_ah_instance_name['installer_package'] }}"
        #src: "{{ hostvars['localhost']['installer_package'] }}"
        dest: ~/aap2

    - name: Get aap2 folder name
      find:
        paths: ~/aap2
        file_type: directory
      register: untar

    - name: Print var
      debug:
        var: untar.files[0].path

    - name: Copy inventory for controller
      copy:
        src: inventory-hub
        dest: "{{ untar.files[0].path }}/inventory"

    - name: Install Automation Hub
      ansible.builtin.shell:
        cmd: ./setup.sh
        chdir: "{{ untar.files[0].path }}"
      become: true        

    - name: Reboot server
      reboot:
      become: true